version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3500:3500"
    volumes:
      - ./backend/logs.json:/app/logs.json
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
